name: Close old data request issues
on:
  schedule:
    - cron: '0 0 * * *'  # Run this workflow every day at midnight
  workflow_dispatch:

env:
  DAYS: 7
jobs:
  closeOldIssues:
    runs-on: ubuntu-latest
    steps:
      - name: Close old data request issues
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const max_age = process.env.DAYS * 24 * 60 * 60 * 1000;
            const now = new Date();
            const issues = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'data request',
              state: 'open'
            });
            for (const issue of issues.data) {
              const createdAt = new Date(issue.created_at);
              if (now - createdAt > max_age) {
                await github.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed'
                });
              }
            }
