name: Forward request to PR
on:
  issues:
    types: [labeled]

jobs:
  createPullRequest:
    if: github.event.label.name == 'data request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create new branch and commit
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git checkout -b issue-${{ github.event.issue.number }}/request
          echo "${{ github.event.issue.number }}" > issue.txt
          git add issue.txt
          git commit -m "Add file for issue #${{ github.event.issue.number }}"
          git push origin issue-${{ github.event.issue.number }}/request
