name: Verify User Input
on:
  issues:
    types: [labeled, edited]

jobs:
  validateInput:
    if: github.event.label.name == 'data request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Create issue file
        run: |
          echo "${{ github.event.issue.number }}" > issue.txt
      - name: Validate user input
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 src/validate_user_input.py --auth_token $GITHUB_TOKEN --issue_id_file issue.txt

      - name: Add 'verified' label to issue
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['verified']
            })
